### ISSUE TITLE
t.elected.boundaries is not a function

### ISSUE THREAD

**Issue by craftzingdev** [prismicio/prismic-dom#47]
When trying to get the HTML from a rich text in prismic we get following error in React Native

t.elected.boundaries is not a function

`RichText.asHtml(item['paragraph-rich-text'], () => console.log('handle link'))
`
When we try asText it succeeds. But we need HTML.

Anyone having the same problem?

Thanks!

**Comment by lihbr** [comment]
Hey @Pointbreak-dev, I'm really sorry you didn't get proper support back then. Usually, you can get support quickly using our [community forum](https://community.prismic.io/c/kits-and-dev-languages/react/15). I hope you figured out a way to solve your issue since then and therefore I'm closing it for now. Feel free to reopen if anything!
